    name: outvisionxr
    description: "A new Flutter project."
    publish_to: 'none'

    version: 1.0.0+1

    environment:
      sdk: ^3.10.3

    dependencies:
      flutter:
        sdk: flutter
      geolocator: ^14.0.2
      google_maps_flutter: ^2.14.0
      google_fonts: ^6.2.1
      cupertino_icons: ^1.0.8
      flutter_localizations:
        sdk: flutter
      shared_preferences: ^2.2.2
      provider: ^6.0.5

    dev_dependencies:
      flutter_test:
        sdk: flutter
      flutter_lints: ^6.0.0

    flutter:
      generate: true # &lt;--- DEVE ESTAR AQUI
      uses-material-design: true
      assets:
        - assets/images/