name: outvisionxr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  permission_handler: ^11.3.1
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Seus pacotes existentes
  google_fonts: ^6.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0

  # DEPENDÊNCIAS DO SLANG (ATUALIZADAS)
  slang: ^3.30.0
  slang_flutter: ^3.30.0
  firebase_core: ^4.4.0
  firebase_database: ^12.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # DEPENDÊNCIAS DE DESENVOLVIMENTO DO SLANG (ATUALIZADAS)
  build_runner: ^2.4.8
  slang_build_runner: ^3.30.0

flutter:
  uses-material-design: true
  assets:
    - assets/3dmodels/stateofbeing.glb
